name: First workflow

on: 
  pull_request:
     types: edited
  
jobs: 

  build:
     runs-on: ubuntu-latest
     steps:
        - name: Print
          run: echo 'build'
  test:
     runs-on: windows-latest
     steps:
        - name: Print test - chrome
          run: echo 'test chrome'
          
  deploy:
     runs-on: ubuntu-latest
     steps:
        - name: Print deploy
          run: echo 'deploy'
